/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    Introduction: typeof import('./src/components/Introduction.vue')['default']
    Portafolio: typeof import('./src/components/Portafolio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./src/components/Skills.vue')['default']
    SocialLinks: typeof import('./src/components/SocialLinks.vue')['default']
    SplashScreen: typeof import('./src/components/SplashScreen.vue')['default']
  }
}
